Repository lit/lit, pull requests merged in 2021-04, with the labels that each got.

#1714 Add `literal` tag to static module.
  packages/lit-html/src/static.ts
  packages/lit-html/src/test/static_test.ts
Labels: cla: yes

#1712 Update Code of Conduct
  CODE_OF_CONDUCT.md
Labels: cla: yes

#1654 [lit-html] add Lit 2 directive syntax to Lit 1
  .gitignore
  src/async-directive.ts
  src/directive-helpers.ts
  src/directive.ts
  src/test/directives/migration-directives_test.ts
  test/index.html
Labels: cla: yes

#1716 Lit next readme
  README.md
Labels: cla: yes

#1723 Fix XLIFF header and config schema link
  packages/localize-tools/CHANGELOG.md
  packages/localize-tools/package.json
  packages/localize-tools/src/formatters/xliff.ts
  packages/localize-tools/testdata/extract-xliff/goldens/data/xliff/es-419.xlf
  packages/localize-tools/testdata/extract-xliff/goldens/data/xliff/zh_CN.xlf
  packages/localize/README.md
Labels: cla: no

#1692 Export part types as type-only, instead of custom `Interface<T>`.
  packages/lit-html/src/directive-helpers.ts
  packages/lit-html/src/hydrate.ts
  packages/lit-html/src/lit-html.ts
  packages/lit-html/src/test/lit-html_test.ts
Labels: cla: yes

#1719 Small fixes to 1.3.0 release ntoes
  docs/guide/release-notes/1.3.0.md
Labels: cla: yes

#1725 Correct evasive typo
  docs/guide/07-concepts.md
Labels: cla: yes

#1732 Ensures `hostConnected` is called only once for element upgrade or late added controllers
  packages/reactive-element/CHANGELOG.md
  packages/reactive-element/src/reactive-element.ts
  packages/reactive-element/src/test/reactive-element-controllers_test.ts
Labels: cla: yes

#1727 [lit-next] scoped registries typings (wrong path)
  packages/labs/scoped-registry-mixin/package.json
Labels: cla: yes

#1735 [reactive-element] Add '@lit/reactive-element/decorators/base.js' to the grouped decorator exports.
  packages/lit-element/src/decorators.ts
  packages/reactive-element/src/decorators.ts
Labels: cla: yes

#1729 [labs] When publishing we also need to include some files form the development folder
  packages/labs/scoped-registry-mixin/package.json
Labels: cla: no

#1724 [lit-html] Add version-stability test
  .eslintignore
  .eslintrc.json
  .prettierignore
  packages/lit-html/.gitignore
  packages/lit-html/package.json
  packages/lit-html/rollup-version-stability-test.config.js
  packages/lit-html/rollup.config.js
  packages/lit-html/src/test/version-stability_test.js
  rollup-common.js
Labels: cla: yes

#1698 [lit-html] Skip walking text nodes
  packages/labs/ssr/src/lib/render-lit-html.ts
  packages/labs/ssr/src/test/integration/tests/basic.ts
  packages/lit-html/src/lit-html.ts
  packages/lit-html/src/test/lit-html_test.ts
Labels: cla: yes

#1741 [labs/ssr] Replace karma with wtr for SSR integration tests
  packages/labs/ssr/.vscode/launch.json
  packages/labs/ssr/package-lock.json
  packages/labs/ssr/package.json
  packages/labs/ssr/src/test/integration/client/basic_test.ts
  packages/labs/ssr/src/test/integration/server/server.ts
  packages/labs/ssr/src/test/integration/test.ts
  packages/labs/ssr/src/test/integration/tests/basic.ts
  packages/labs/ssr/web-test-runner.config.js
Labels: cla: yes

#1742 [lit-next] Update top-level and test deps
  .github/workflows/benchmarks.yml
  .github/workflows/tests.yml
  package-lock.json
  package.json
  packages/tests/package-lock.json
  packages/tests/package.json
Labels: cla: yes

#1743 [lit-next] Rename hydrate & hydrate-support to "experimental"
  .eslintignore
  .prettierignore
  packages/labs/ssr-client/package.json
  packages/labs/ssr/src/demo/app-client.ts
  packages/labs/ssr/src/lib/render-lit-html.ts
  packages/labs/ssr/src/test/integration/client/basic_test.ts
  packages/labs/ssr/src/test/integration/tests/basic.ts
  packages/labs/ssr/src/test/test-files/render-test-module.ts
  packages/lit-element/.gitignore
  packages/lit-element/CHANGELOG.md
  packages/lit-element/package.json
  packages/lit-element/rollup.config.js
  packages/lit-element/src/experimental-hydrate-support.ts
  packages/lit-html/.gitignore
  packages/lit-html/CHANGELOG.md
  packages/lit-html/package.json
  packages/lit-html/rollup.config.js
  packages/lit-html/src/experimental-hydrate.ts
  packages/lit/.gitignore
  packages/lit/CHANGELOG.md
  packages/lit/README.md
  packages/lit/package.json
  packages/lit/rollup.config.js
  packages/lit/src/experimental-hydrate-support.ts
  packages/lit/src/experimental-hydrate.ts
  rollup-common.js
Labels: cla: yes

#1747 Add description and badges to readme
  README.md
Labels: cla: yes

#1749 Fix @lit-labs/ssr-client link
  README.md
Labels: cla: yes

#1388 [lit-ssr] Add defer-hydration protocol for coordinating host/child hydration
  packages/labs/ssr/CHANGELOG.md
  packages/labs/ssr/src/lib/element-renderer.ts
  packages/labs/ssr/src/lib/lit-element-renderer.ts
  packages/labs/ssr/src/lib/render-lit-html.ts
  packages/labs/ssr/src/test/integration/tests/basic.ts
  packages/labs/ssr/src/test/lit/render-lit_test.ts
  packages/lit-element/CHANGELOG.md
  packages/lit-element/src/experimental-hydrate-support.ts
  packages/lit-html/CHANGELOG.md
  packages/lit-html/src/experimental-hydrate.ts
  packages/tests/package-lock.json
Labels: cla: yes

#1748 Small tweaks to forward-compat directives
  .eslintrc.json
  src/directive.ts
Labels: cla: yes

#1750 Updates from moving lit-next branch to main
  CONTRIBUTING.md
  README.md
  lit-next.code-workspace
  packages/benchmarks/README.md
  packages/benchmarks/generator/scripts/package-versions-tot.json
  packages/benchmarks/lit-element/list/index.ts
  packages/benchmarks/lit-element/list/tachometer-render.json
  packages/benchmarks/lit-element/list/tachometer-update-reflect.json
  packages/benchmarks/lit-element/list/tachometer-update.json
  packages/benchmarks/lit-element/list/tachometer.json
  packages/benchmarks/lit-html/kitchen-sink/tachometer-nop-update.json
  packages/benchmarks/lit-html/kitchen-sink/tachometer-render.json
  packages/benchmarks/lit-html/kitchen-sink/tachometer-update.json
  packages/benchmarks/lit-html/kitchen-sink/tachometer.json
  packages/benchmarks/lit-html/repeat/tachometer-full.json
  packages/benchmarks/lit-html/repeat/tachometer.json
  packages/benchmarks/lit-html/template-heavy/tachometer.json
  packages/benchmarks/reactive-element/list/tachometer-render.json
  packages/benchmarks/reactive-element/list/tachometer-update-reflect.json
  packages/benchmarks/reactive-element/list/tachometer-update.json
  packages/benchmarks/reactive-element/list/tachometer.json
  packages/lit-element/README.md
  packages/lit-element/src/lit-element.ts
  packages/lit-html/README.md
  packages/lit/package.json
  packages/localize-tools/README.md
  packages/localize-tools/package.json
  packages/localize-tools/src/cli.ts
  packages/localize/README.md
  packages/localize/examples/runtime/README.md
  packages/localize/examples/transform/README.md
  packages/localize/package.json
  packages/reactive-element/README.md
  packages/reactive-element/src/reactive-element.ts
Labels: cla: yes, lit-next

#1733 [localize] Add XLIFF e2e test for merging existing translations with new messages
  packages/localize-tools/src/tests/e2e/extract-xlb-fresh.test.ts
  packages/localize-tools/src/tests/e2e/extract-xliff-fresh.test.ts
  packages/localize-tools/src/tests/e2e/extract-xliff-merge.test.ts
  packages/localize-tools/src/tests/format-dir-diff.ts
  packages/localize-tools/testdata/extract-xlb-fresh/goldens/foo.ts
  packages/localize-tools/testdata/extract-xlb-fresh/goldens/lit-localize.json
  packages/localize-tools/testdata/extract-xlb-fresh/goldens/tsconfig.json
  packages/localize-tools/testdata/extract-xlb-fresh/goldens/tsout/empty.txt
  packages/localize-tools/testdata/extract-xlb-fresh/goldens/xlb/empty.txt
  packages/localize-tools/testdata/extract-xlb-fresh/goldens/xlb/en.xlb
  packages/localize-tools/testdata/extract-xlb-fresh/input/foo.ts
  packages/localize-tools/testdata/extract-xlb-fresh/input/lit-localize.json
  packages/localize-tools/testdata/extract-xlb-fresh/input/tsconfig.json
  packages/localize-tools/testdata/extract-xlb-fresh/input/tsout/empty.txt
  packages/localize-tools/testdata/extract-xlb-fresh/input/xlb/empty.txt
  packages/localize-tools/testdata/extract-xliff-fresh/goldens/data/xliff/es-419.xlf
  packages/localize-tools/testdata/extract-xliff-fresh/goldens/data/xliff/zh_CN.xlf
  packages/localize-tools/testdata/extract-xliff-fresh/goldens/foo.ts
  packages/localize-tools/testdata/extract-xliff-fresh/goldens/lit-localize.json
  packages/localize-tools/testdata/extract-xliff-fresh/goldens/tsconfig.json
  packages/localize-tools/testdata/extract-xliff-fresh/input/foo.ts
  packages/localize-tools/testdata/extract-xliff-fresh/input/lit-localize.json
  packages/localize-tools/testdata/extract-xliff-fresh/input/tsconfig.json
  packages/localize-tools/testdata/extract-xliff-merge/goldens/foo.ts
  packages/localize-tools/testdata/extract-xliff-merge/goldens/lit-localize.json
  packages/localize-tools/testdata/extract-xliff-merge/goldens/tsconfig.json
  packages/localize-tools/testdata/extract-xliff-merge/goldens/xliff/es-419.xlf
  packages/localize-tools/testdata/extract-xliff-merge/input/foo.ts
  packages/localize-tools/testdata/extract-xliff-merge/input/lit-localize.json
  packages/localize-tools/testdata/extract-xliff-merge/input/tsconfig.json
  packages/localize-tools/testdata/extract-xliff-merge/input/xliff/es-419.xlf
Labels: cla: yes

#1757 [lit-html] Add and export type HTMLTemplateResult
  packages/lit-html/src/lit-html.ts
Labels: cla: yes

#1760 [all] Fix Husky after upgrade to v6
  .husky/.gitignore
  .husky/pre-commit
  package.json
Labels: cla: yes

#1763 [lit-html] Mark Template as internal to skip API docs
  packages/lit-html/src/lit-html.ts
Labels: cla: yes

#1761 [reactive-element] Fix @customElement() jsdoc example
  packages/reactive-element/src/decorators/custom-element.ts
Labels: Area: docs, cla: yes

#1767 [localize] Upgrade to Lit 2 and add @localized decorator
  .eslintignore
  .prettierignore
  lerna.json
  packages/localize-tools/CHANGELOG.md
  packages/localize-tools/package-lock.json
  packages/localize-tools/package.json
  packages/localize-tools/src/messages.ts
  packages/localize-tools/src/modes/runtime.ts
  packages/localize-tools/src/modes/transform.ts
  packages/localize-tools/src/program-analysis.ts
  packages/localize-tools/src/tests/transform.unit.test.ts
  packages/localize-tools/testdata/build-runtime-xlb/goldens/foo.ts
  packages/localize-tools/testdata/build-runtime-xlb/goldens/tsout/es-419.ts
  packages/localize-tools/testdata/build-runtime-xlb/input/foo.ts
  packages/localize-tools/testdata/build-runtime-xliff/goldens/foo.ts
  packages/localize-tools/testdata/build-runtime-xliff/goldens/tsout/es-419.ts
  packages/localize-tools/testdata/build-runtime-xliff/goldens/tsout/zh_CN.ts
  packages/localize-tools/testdata/build-runtime-xliff/input/foo.ts
  packages/localize-tools/testdata/build-transform-xliff/goldens/foo.ts
  packages/localize-tools/testdata/build-transform-xliff/goldens/tsconfig.json
  packages/localize-tools/testdata/build-transform-xliff/goldens/tsout/en/foo.js
  packages/localize-tools/testdata/build-transform-xliff/goldens/tsout/es-419/foo.js
  packages/localize-tools/testdata/build-transform-xliff/goldens/tsout/zh_CN/foo.js
  packages/localize-tools/testdata/build-transform-xliff/input/foo.ts
  packages/localize-tools/testdata/build-transform-xliff/input/tsconfig.json
  packages/localize-tools/testdata/extract-xlb-fresh/goldens/foo.ts
  packages/localize-tools/testdata/extract-xlb-fresh/input/foo.ts
  packages/localize-tools/testdata/extract-xliff-fresh/goldens/foo.ts
  packages/localize-tools/testdata/extract-xliff-fresh/input/foo.ts
  packages/localize-tools/testdata/placeholder-errors/goldens/foo.ts
  packages/localize-tools/testdata/placeholder-errors/input/foo.ts
  packages/localize/.gitignore
  packages/localize/CHANGELOG.md
  packages/localize/README.md
  packages/localize/examples/runtime/.gitignore
  packages/localize/examples/runtime/package-lock.json
  packages/localize/examples/runtime/package.json
  packages/localize/examples/runtime/src/index.ts
  packages/localize/examples/runtime/src/locale-picker.ts
  packages/localize/examples/runtime/src/locales/es-419.ts
  packages/localize/examples/runtime/src/locales/zh_CN.ts
  packages/localize/examples/runtime/src/x-greeter.ts
  packages/localize/examples/runtime/tsconfig.json
  packages/localize/examples/transform/.gitignore
  packages/localize/examples/transform/package-lock.json
  packages/localize/examples/transform/package.json
  packages/localize/examples/transform/src/locale-picker.ts
  packages/localize/examples/transform/src/x-greeter.ts
  packages/localize/package-lock.json
  packages/localize/package.json
  packages/localize/src/lit-localize.ts
  packages/localize/src/localized-element.ts
  packages/localize/src/tests/lit-localize.test.ts
  packages/localize/tsconfig.json
Labels: cla: yes

#1770 Fix localize-tools link
  README.md
Labels: cla: yes

#1769 Fix CONTRIBUTING link
  README.md
Labels: cla: yes

#1765 [scoped-registry-mixin] adopt styles
  packages/labs/scoped-registry-mixin/package.json
  packages/labs/scoped-registry-mixin/src/scoped-registry-mixin.ts
  packages/labs/scoped-registry-mixin/src/test/scoped-registry-mixin_test.ts
Labels: cla: yes

#1768 Release localize 0.10.0 and localize-tools 0.3.0
  packages/localize-tools/CHANGELOG.md
  packages/localize-tools/package-lock.json
  packages/localize-tools/package.json
  packages/localize/CHANGELOG.md
  packages/localize/examples/runtime/package.json
  packages/localize/examples/transform/package.json
  packages/localize/package.json
Labels: cla: yes

#1771 Simplify ESLint config
  .eslintrc.json
  packages/labs/ssr/package.json
Labels: cla: yes

#1745 [labs] Adds a motion labs package containing a flip directive
  .eslintignore
  .prettierignore
  packages/labs/motion/.gitignore
  packages/labs/motion/CHANGELOG.md
  packages/labs/motion/LICENSE
  packages/labs/motion/README.md
  packages/labs/motion/demo/animation.html
  packages/labs/motion/demo/delete.svg
  packages/labs/motion/demo/hero.html
  packages/labs/motion/demo/index.html
  packages/labs/motion/demo/list.html
  packages/labs/motion/demo/lists.html
  packages/labs/motion/demo/lit-logo.html
  packages/labs/motion/demo/lit.html
  packages/labs/motion/demo/scaling.html
  packages/labs/motion/demo/simple.html
  packages/labs/motion/demo/tabs.html
  packages/labs/motion/package-lock.json
  packages/labs/motion/package.json
  packages/labs/motion/rollup.config.js
  packages/labs/motion/scripts/dev.sh
  packages/labs/motion/src/flip-controller.ts
  packages/labs/motion/src/flip.ts
  packages/labs/motion/src/index.ts
  packages/labs/motion/src/position.ts
  packages/labs/motion/src/test/flip_controller_test.ts
  packages/labs/motion/src/test/flip_test.ts
  packages/labs/motion/src/test/test-helpers.ts
  packages/labs/motion/tsconfig.json
Labels: cla: yes

#1532 [labs/react] Add useController() hook
  .eslintignore
  .prettierignore
  packages/labs/react/.gitignore
  packages/labs/react/CHANGELOG.md
  packages/labs/react/README.md
  packages/labs/react/package.json
  packages/labs/react/rollup.config.js
  packages/labs/react/src/test/use-controller_test.ts
  packages/labs/react/src/use-controller.ts
Labels: cla: yes, lit-next

#1762 [lit-html] Remove unneeded bindingIndex variable
  packages/lit-html/src/lit-html.ts
  packages/lit-html/src/test/lit-html_test.ts
Labels: cla: yes

#1775 README tweaks
  README.md
  packages/lit/README.md
Labels: cla: yes

#1774 Update motion & scoped-registry authors
  packages/labs/motion/LICENSE
  packages/labs/motion/package.json
  packages/labs/scoped-registry-mixin/LICENSE
  packages/labs/scoped-registry-mixin/package.json
Labels: cla: yes

#1776 Add @lit-labs/motion to README
  README.md
Labels: cla: yes

#1772 Add TrustedTypes support to lit-next
  packages/labs/ssr/src/lib/render-lit-html.ts
  packages/lit-html/CHANGELOG.md
  packages/lit-html/src/lit-html.ts
  packages/lit-html/src/test/lit-html_test.ts
Labels: cla: yes

#1773 [all] Release rc 1
  packages/benchmarks/generator/package.json
  packages/benchmarks/package.json
  packages/internal-scripts/package.json
  packages/labs/motion/CHANGELOG.md
  packages/labs/motion/package-lock.json
  packages/labs/motion/package.json
  packages/labs/react/CHANGELOG.md
  packages/labs/react/package-lock.json
  packages/labs/react/package.json
  packages/labs/scoped-registry-mixin/CHANGELOG.md
  packages/labs/scoped-registry-mixin/package-lock.json
  packages/labs/scoped-registry-mixin/package.json
  packages/labs/ssr-client/CHANGELOG.md
  packages/labs/ssr-client/package-lock.json
  packages/labs/ssr-client/package.json
  packages/labs/ssr/CHANGELOG.md
  packages/labs/ssr/package-lock.json
  packages/labs/ssr/package.json
  packages/labs/task/CHANGELOG.md
  packages/labs/task/package-lock.json
  packages/labs/task/package.json
  packages/lit-element/CHANGELOG.md
  packages/lit-element/package-lock.json
  packages/lit-element/package.json
  packages/lit-element/src/lit-element.ts
  packages/lit-html/CHANGELOG.md
  packages/lit-html/package-lock.json
  packages/lit-html/package.json
  packages/lit-html/src/lit-html.ts
  packages/lit-starter-js/package-lock.json
  packages/lit-starter-js/package.json
  packages/lit-starter-ts/package-lock.json
  packages/lit-starter-ts/package.json
  packages/lit/CHANGELOG.md
  packages/lit/package-lock.json
  packages/lit/package.json
  packages/localize-tools/CHANGELOG.md
  packages/localize-tools/package-lock.json
  packages/localize-tools/package.json
  packages/localize/CHANGELOG.md
  packages/localize/examples/runtime/package.json
  packages/localize/examples/transform/package.json
  packages/localize/package-lock.json
  packages/localize/package.json
  packages/reactive-element/CHANGELOG.md
  packages/reactive-element/package-lock.json
  packages/reactive-element/package.json
  packages/reactive-element/src/reactive-element.ts
Labels: cla: yes

#1781 Release rc2
  packages/lit-html/CHANGELOG.md
  packages/lit-html/package-lock.json
  packages/lit-html/package.json
  packages/lit-html/src/lit-html.ts
Labels: cla: yes

#1782 [labs/ssr] Update README.md
  packages/labs/ssr/README.md
Labels: cla: yes

#1779 [lit-html] Update Twitter handle from polymer -> buildWithLit
  docs/_includes/default.html
  docs/guide/09-community.md
Labels: cla: yes

#1783 [all] Update lit, lit-html, and lit-element READMEs
  packages/lit-element/README.md
  packages/lit-html/README.md
  packages/lit/README.md
  packages/lit/logo.png
Labels: cla: yes

#1785 Update starter kit versions
  packages/lit-starter-js/docs/my-element.bundled.js
  packages/lit-starter-js/package-lock.json
  packages/lit-starter-js/package.json
  packages/lit-starter-ts/docs/examples/name-property/index.html
  packages/lit-starter-ts/docs/index.html
  packages/lit-starter-ts/docs/install/index.html
  packages/lit-starter-ts/docs/my-element.bundled.js
  packages/lit-starter-ts/docs/prism-okaidia.css
  packages/lit-starter-ts/package-lock.json
  packages/lit-starter-ts/package.json
Labels: cla: yes

#1787 Changing links to the new repository
  README.md
Labels: cla: yes

#1788 Updating links to the new repository
  README.md
Labels: cla: yes

#1795 [all] Remove Polymer references and update links
  .editorconfig
  .github/ISSUE_TEMPLATE/bug_report.md
  CONTRIBUTING.md
  packages/benchmarks/README.md
  packages/labs/motion/demo/animation.html
  packages/labs/motion/demo/hero.html
  packages/labs/motion/demo/index.html
  packages/labs/motion/demo/list.html
  packages/labs/motion/demo/lists.html
  packages/labs/motion/demo/lit-logo.html
  packages/labs/motion/demo/lit.html
  packages/labs/motion/demo/scaling.html
  packages/labs/motion/demo/simple.html
  packages/labs/motion/demo/tabs.html
  packages/labs/motion/rollup.config.js
  packages/labs/motion/scripts/dev.sh
  packages/labs/motion/src/index.ts
  packages/labs/motion/src/test/flip_controller_test.ts
  packages/labs/motion/src/test/flip_test.ts
  packages/labs/motion/src/test/test-helpers.ts
  packages/labs/react/src/test/use-controller_test.ts
  packages/labs/react/src/use-controller.ts
  packages/labs/scoped-registry-mixin/rollup.config.js
  packages/labs/scoped-registry-mixin/scripts/dev.sh
  packages/labs/scoped-registry-mixin/src/scoped-registry-mixin.ts
  packages/labs/scoped-registry-mixin/src/test/scoped-registry-mixin_test.ts
  packages/labs/ssr/README.md
  packages/lit-element/src/lit-element.ts
  packages/lit-html/src/experimental-hydrate.ts
  packages/lit-html/src/lit-html.ts
  packages/lit-html/src/test/directives/class-map_test.ts
  packages/lit-html/src/test/directives/template-content_test.ts
  packages/lit-starter-js/README.md
  packages/lit-starter-ts/README.md
  packages/localize-tools/README.md
  packages/localize-tools/src/cli.ts
  packages/localize-tools/src/config.ts
  packages/localize-tools/testdata/build-runtime-xlb/goldens/foo.ts
  packages/localize-tools/testdata/build-runtime-xlb/goldens/lit-localize.json
  packages/localize-tools/testdata/build-runtime-xlb/input/foo.ts
  packages/localize-tools/testdata/build-runtime-xliff/goldens/foo.ts
  packages/localize-tools/testdata/build-runtime-xliff/input/foo.ts
  packages/localize-tools/testdata/build-transform-xliff/goldens/foo.ts
  packages/localize-tools/testdata/build-transform-xliff/goldens/tsout/en/foo.js
  packages/localize-tools/testdata/build-transform-xliff/goldens/tsout/es-419/foo.js
  packages/localize-tools/testdata/build-transform-xliff/goldens/tsout/zh_CN/foo.js
  packages/localize-tools/testdata/build-transform-xliff/input/foo.ts
  packages/localize-tools/testdata/extract-xlb-fresh/goldens/lit-localize.json
  packages/localize/README.md
  packages/localize/examples/runtime/README.md
  packages/localize/examples/runtime/lit-localize.json
  packages/localize/examples/transform/README.md
  packages/localize/examples/transform/lit-localize.json
  packages/reactive-element/README.md
  packages/reactive-element/src/reactive-element.ts
Labels: cla: yes

#1792 chore: update benchmark repo paths
  packages/benchmarks/generator/scripts/package-versions-tot.json
  packages/benchmarks/lit-element/list/tachometer-render.json
  packages/benchmarks/lit-element/list/tachometer-update-reflect.json
  packages/benchmarks/lit-element/list/tachometer-update.json
  packages/benchmarks/lit-element/list/tachometer.json
  packages/benchmarks/lit-html/kitchen-sink/tachometer-nop-update.json
  packages/benchmarks/lit-html/kitchen-sink/tachometer-render.json
  packages/benchmarks/lit-html/kitchen-sink/tachometer-update.json
  packages/benchmarks/lit-html/kitchen-sink/tachometer.json
  packages/benchmarks/lit-html/repeat/tachometer-full.json
  packages/benchmarks/lit-html/repeat/tachometer.json
  packages/benchmarks/lit-html/template-heavy/tachometer.json
  packages/benchmarks/reactive-element/list/tachometer-render.json
  packages/benchmarks/reactive-element/list/tachometer-update-reflect.json
  packages/benchmarks/reactive-element/list/tachometer-update.json
  packages/benchmarks/reactive-element/list/tachometer.json
Labels: cla: yes

#1799 [@lit-labs/motion] Fix package.json's files section to include flip-controller.
  packages/labs/motion/CHANGELOG.md
  packages/labs/motion/package.json
Labels: cla: yes

#1800 Fix nuke
  .prettierignore
  .prettierignore-sync
  package.json
Labels: cla: yes

#1786 Add lit.dev banner on lit-html site.
  docs/_includes/post.html
  docs/_includes/version-banner.html
  docs/css/main.css
  docs/images/flame.svg
  docs/main.py
Labels: cla: yes

#1801 "disconnet" -> "disconnect"
  packages/lit-html/src/async-directive.ts
  packages/lit-html/src/directive.ts
  packages/lit-html/src/lit-html.ts
  packages/lit-html/src/test/directives/cache_test.ts
  rollup-common.js
Labels: cla: yes

#1820 [labs/react] Fix #1815: useController/requestUpdate bug
  packages/labs/react/CHANGELOG.md
  packages/labs/react/src/test/use-controller_test.ts
  packages/labs/react/src/use-controller.ts
Labels: cla: yes

#1809 [lit-html] Prepare v1.4.0 release
  CHANGELOG.md
  README.md
  package-lock.json
  package.json
  src/lit-html.ts
Labels: cla: yes

#1814 [readme] Switch monorepo readme links to lit.dev and add logo
  README.md
Labels: cla: yes

#1790 [reactive-element] update "name" type to "PropertyKey"
  packages/reactive-element/src/decorators/base.ts
  packages/reactive-element/src/test/decorators/queryAssignedNodes_test.ts
Labels: cla: yes

#1824 [labs/task] Add task.js to package exports
  packages/labs/task/CHANGELOG.md
  packages/labs/task/package.json
Labels: cla: yes

#1828 [labs/react] Omit 'children' from element type in props
  packages/labs/react/src/create-component.ts
  packages/labs/react/src/test/create-component_test.tsx
  packages/labs/react/tsconfig.json
Labels: cla: yes
