Repository lit/lit, pull requests merged in 2021-01, with the labels that each got.

#1524 [lit-next] Fix failing IE tests
  packages/lit-element/src/test/platform-support/lit-element-sd-ce-cp_test.html
  packages/lit-element/src/test/platform-support/lit-element-sd-ce_test.html
  packages/lit-element/src/test/platform-support/lit-element-sd_test.html
  packages/lit-element/src/test/platform-support/lit-element_test.html
  packages/lit-html/src/test/platform-support/lit-html-apply_test.html
  packages/lit-html/src/test/platform-support/lit-html-no-wc_test.html
  packages/lit-html/src/test/platform-support/lit-html-scoping-shim_test.html
  packages/lit-html/src/test/platform-support/lit-html_test.html
  packages/reactive-element/src/test/platform-support/reactive-element-sd-ce-cp_test.html
  packages/reactive-element/src/test/platform-support/reactive-element-sd-ce_test.html
  packages/reactive-element/src/test/platform-support/reactive-element-sd_test.html
  packages/reactive-element/src/test/platform-support/reactive-element_test.html
  packages/tests/web-test-runner.config.js
Labels: cla: yes

#1520 [lit-next] Nested directives whose parent returns `noChange` are unaffected
  packages/lit-html/CHANGELOG.md
  packages/lit-html/src/lit-html.ts
  packages/lit-html/src/test/directives/guard_test.ts
  packages/lit-html/src/test/lit-html_test.ts
Labels: Focus Area: Core Libraries, Why: Enable new use cases, cla: yes, lit-next

#1506 [lit-next] Give private exports unique names
  packages/lit-element/src/lit-element.ts
  packages/lit-element/src/private-ssr-support.ts
  packages/lit-html/src/directive-helpers.ts
  packages/lit-html/src/directive.ts
  packages/lit-html/src/hydrate.ts
  packages/lit-html/src/lit-html.ts
  packages/lit-html/src/private-ssr-support.ts
  packages/lit-ssr/src/lib/lit-element-renderer.ts
  packages/lit-ssr/src/lib/render-lit-html.ts
Labels: cla: yes

#1528 [lit-next] remove demos from Lit/ReactiveElement
  packages/lit-element/demo/bundle.html
  packages/lit-element/demo/lit-element.html
  packages/lit-element/demo/platform-support.html
  packages/lit-element/package.json
  packages/lit-element/rollup.bundle.config.js
  packages/lit-element/rollup.config.js
  packages/lit-element/src/demo/my-element.ts
  packages/lit-element/src/test/platform-support/lit-element-bundle_test.html
  packages/reactive-element/demo/index.html
  packages/reactive-element/src/demo/ts-element.ts
  packages/tests/web-test-runner.config.js
  rollup-common.js
Labels: cla: yes

#1542 Fix ElementPart when IE reorders attrs. Fixes #1537
  packages/lit-html/src/hydrate.ts
  packages/lit-html/src/lit-html.ts
  packages/lit-html/src/private-ssr-support.ts
  packages/lit-html/src/test/lit-html_test.ts
  packages/lit-ssr/src/lib/render-lit-html.ts
  packages/lit-ssr/src/test/integration/tests/basic.ts
Labels: cla: yes

#1525 Optionally enables support for `ShadyDOM.noPatch` setting
  packages/lit-element/package-lock.json
  packages/lit-element/package.json
  packages/lit-element/src/env.d.ts
  packages/lit-element/src/test/platform-support/lit-element-ce-sd-noPatch_test.html
  packages/lit-element/src/test/test-helpers.ts
  packages/lit-html/package-lock.json
  packages/lit-html/package.json
  packages/lit-html/src/directive-helpers.ts
  packages/lit-html/src/env.d.ts
  packages/lit-html/src/lit-html.ts
  packages/lit-html/src/platform-support.ts
  packages/lit-html/src/test/directives/cache_test.ts
  packages/lit-html/src/test/platform-support/lit-html-noPatch_test.html
  packages/lit-html/src/test/platform-support/lit-html_html-test.ts
  packages/lit-html/src/test/test-utils/shadow-root.ts
  packages/reactive-element/package-lock.json
  packages/reactive-element/package.json
  packages/reactive-element/src/env.d.ts
  packages/reactive-element/src/platform-support.ts
  packages/reactive-element/src/test/platform-support/reactive-element-ce-sd-noPatch_test.html
  packages/reactive-element/src/test/test-helpers.ts
  rollup-common.js
Labels: cla: yes

#1540 [lit-next] Renames `platform-support` to `polyfill-support`
  .eslintignore
  .prettierignore
  packages/lit-element/.gitignore
  packages/lit-element/CHANGELOG.md
  packages/lit-element/package.json
  packages/lit-element/rollup.config.js
  packages/lit-element/src/polyfill-support.ts
  packages/lit-element/src/test/lit-element_styling_apply_test.ts
  packages/lit-element/src/test/polyfill-support/lit-element-ce-sd-noPatch_test.html
  packages/lit-element/src/test/polyfill-support/lit-element-sd-ce-cp_test.html
  packages/lit-element/src/test/polyfill-support/lit-element-sd-ce_test.html
  packages/lit-element/src/test/polyfill-support/lit-element-sd_test.html
  packages/lit-element/src/test/polyfill-support/lit-element_html-test.ts
  packages/lit-element/src/test/polyfill-support/lit-element_test.html
  packages/lit-html/.gitignore
  packages/lit-html/CHANGELOG.md
  packages/lit-html/package.json
  packages/lit-html/rollup.config.js
  packages/lit-html/src/lit-html.ts
  packages/lit-html/src/polyfill-support.ts
  packages/lit-html/src/test/polyfill-support/lit-html-apply_html-test.ts
  packages/lit-html/src/test/polyfill-support/lit-html-apply_test.html
  packages/lit-html/src/test/polyfill-support/lit-html-no-wc_html-test.ts
  packages/lit-html/src/test/polyfill-support/lit-html-no-wc_test.html
  packages/lit-html/src/test/polyfill-support/lit-html-noPatch_test.html
  packages/lit-html/src/test/polyfill-support/lit-html-scoping-shim_html-test.ts
  packages/lit-html/src/test/polyfill-support/lit-html-scoping-shim_test.html
  packages/lit-html/src/test/polyfill-support/lit-html_html-test.ts
  packages/lit-html/src/test/polyfill-support/lit-html_test.html
  packages/lit/.gitignore
  packages/lit/CHANGELOG.md
  packages/lit/README.md
  packages/lit/package.json
  packages/lit/rollup.config.js
  packages/lit/src/polyfill-support.ts
  packages/lit/src/test/lit-element-bundle_test.html
  packages/reactive-element/.gitignore
  packages/reactive-element/package.json
  packages/reactive-element/rollup.config.js
  packages/reactive-element/src/polyfill-support.ts
  packages/reactive-element/src/reactive-element.ts
  packages/reactive-element/src/test/polyfill-support/reactive-element-ce-sd-noPatch_test.html
  packages/reactive-element/src/test/polyfill-support/reactive-element-sd-ce-cp_test.html
  packages/reactive-element/src/test/polyfill-support/reactive-element-sd-ce_test.html
  packages/reactive-element/src/test/polyfill-support/reactive-element-sd_test.html
  packages/reactive-element/src/test/polyfill-support/reactive-element_html-test.ts
  packages/reactive-element/src/test/polyfill-support/reactive-element_test.html
  packages/reactive-element/src/test/reactive-element_dev_mode_test.ts
  rollup-common.js
Labels: cla: yes

#1545 [lit-next] Adds `removeController`
  packages/lit-element/src/test/lit-element_test.ts
  packages/reactive-element/CHANGELOG.md
  packages/reactive-element/src/reactive-controller.ts
  packages/reactive-element/src/reactive-element.ts
  packages/reactive-element/src/test/reactive-element-controllers_test.ts
Labels: cla: yes

#1549 [lit-next] Adds `willUpdate` to `lit-element-renderer`
  packages/lit-element/src/lit-element.ts
  packages/lit-element/src/private-ssr-support.ts
  packages/lit-html/src/private-ssr-support.ts
  packages/lit-ssr/src/lib/lit-element-renderer.ts
  packages/lit-ssr/src/lib/render-lit-html.ts
  packages/lit-ssr/src/test/integration/tests/basic.ts
  packages/lit-ssr/src/test/lit/render-lit_test.ts
  packages/lit-ssr/src/test/test-files/render-test-module.ts
  packages/reactive-element/src/reactive-element.ts
  rollup-common.js
Labels: cla: yes, lit-next

#1548 [lit-next] Update Lit/ReactiveElement readmes
  packages/lit-element/README.md
  packages/lit-html/README.md
  packages/reactive-element/README.md
Labels: Focus Area: Core Libraries, cla: yes, lit-next

#1536 [lit-html] Add support for re-parenting Disconnectables. Fixes #1535
  packages/lit-html/src/directive-helpers.ts
  packages/lit-html/src/directives/cache.ts
  packages/lit-html/src/disconnectable-directive.ts
  packages/lit-html/src/lit-html.ts
  packages/lit-html/src/test/directives/cache_test.ts
  packages/lit-html/src/test/polyfill-support/lit-html_html-test.ts
  rollup-common.js
Labels: cla: yes

#1562 Fix typos in 06-template-reference.md
  docs/guide/06-template-reference.md
Labels: cla: yes

#1530 [lit-next] Add TypeScript project references
  .eslintignore
  .gitignore
  .prettierignore
  packages/benchmarks/package.json
  packages/benchmarks/tsconfig.json
  packages/labs/package.json
  packages/labs/tsconfig.json
  packages/lit-element/package.json
  packages/lit-element/tsconfig.json
  packages/lit-html/package.json
  packages/lit-html/tsconfig.json
  packages/lit-ssr/tsconfig.json
  packages/reactive-element/package.json
  packages/reactive-element/tsconfig.json
Labels: cla: yes

#1568 [lit-next] Fix builds by removing `.tsbuildinfo` files
  packages/labs/package.json
  packages/lit-element/package.json
  packages/lit-html/package.json
  packages/lit/package.json
  packages/reactive-element/package.json
Labels: Focus Area: Core Libraries, Why: Improve ergonomics, cla: yes, lit-next

#1570 Minor compilability improvements to lit-html polyfill-support.ts
  packages/lit-html/src/polyfill-support.ts
Labels: cla: yes

#1571 More minor compilability improvements.
  packages/lit-element/src/hydrate-support.ts
  packages/reactive-element/src/polyfill-support.ts
  packages/reactive-element/src/reactive-element.ts
Labels: cla: yes

#1558 [lit-next] Squelches most test error logging to make output less spammy.
  packages/reactive-element/src/test/reactive-element_test.ts
  packages/tests/web-test-runner.config.js
Labels: cla: yes

#1553 [reactive-element] Further refines `ReactiveController` API
  packages/benchmarks/reactive-element/list/index.ts
  packages/labs/react/package-lock.json
  packages/labs/task/src/task.ts
  packages/labs/task/src/test/task_test.ts
  packages/lit-element/src/hydrate-support.ts
  packages/lit-element/src/test/lit-element_test.ts
  packages/lit-html/CHANGELOG.md
  packages/lit-html/src/disconnectable-directive.ts
  packages/lit-html/src/test/directives/cache_test.ts
  packages/reactive-element/CHANGELOG.md
  packages/reactive-element/src/reactive-controller.ts
  packages/reactive-element/src/reactive-element.ts
  packages/reactive-element/src/test/reactive-element-controllers_test.ts
Labels: cla: yes

#1561 [lit-html] Renders `null`, `undefined`, and empty string the same as `nothing` in `ChildPart`
  packages/lit-html/CHANGELOG.md
  packages/lit-html/src/lit-html.ts
  packages/lit-html/src/test/lit-html_test.ts
Labels: cla: yes, lit-next

#1575 [lit-next] Fixes build issues
  package.json
  packages/labs/react/package-lock.json
  packages/labs/react/package.json
  packages/localize/src/formatters/index.ts
Labels: cla: yes

#1574 Adds `_initialize` as an internal method to `ReactiveElement`
  packages/reactive-element/src/reactive-element.ts
Labels: cla: yes
